### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by michalliu** [pingao777/markdown-preview-sync#1]
![image](https://user-images.githubusercontent.com/1010851/43838239-65fdccde-9b4d-11e8-96f0-bb02c1687408.png)

MacVim

**Comment by michalliu** [comment]
原来代码里是windows only

**Comment by naosense** [comment]
Not set browser path
你没设置浏览器路径，参考说明里设置下chrome或firefox的路径

**Comment by michalliu** [comment]
Not set browser path 只是其中一个错误。现在已经自己解决了，提了PR，请review

**Comment by michalliu** [comment]
另外用这个插件的注意，release里面的文件解压出来要全部使用dos2unix转一遍才可以在mac和linux上使用。整体来说这是一个很优秀的插件，我已经集成到我的小项目里去了
https://github.com/michalliu/gvimim-macvim/commits/master

**Comment by naosense** [comment]
Nice work，我的系统是windows，确实没在mac和linux测过
