### ISSUE TITLE
NameError: name 'java_vim_bridge' is not defined

### ISSUE THREAD

**Issue by jarviszeng-zjc** [pingao777/markdown-preview-sync#4]
hello,
I have this problem:

Error detected while processing function mpsync#preview[5]..<SNR>64_open:
line   18:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
NameError: name 'java_vim_bridge' is not defined

macOS Mojave 10.14.1
vim 8.0.1283

Please help, thank you very much.

**Comment by naosense** [comment]
it looks python version does not match vim version,  are they both 32 bit?
